### ISSUE TITLE
Add Code Comments

### ISSUE THREAD

**Issue by island255** [tech-srl/Nero#1]
Thank you for your outstanding job! Now I want to read your code to learn the implementation. 
However, without comments, it is hard to understand them. So please add some comments.
Besides, I wonder if the preprocessing part is in this repo. If not, can you please share it?

**Comment by Yanivmd** [comment]
Thank you for the kind words @island255.
We are working hard on publishing the preprocessing part. Following that, we will try to make all the code as readable as we can. Stay tuned!
