### ISSUE TITLE
there are some problem

### ISSUE THREAD

**Issue by tower111** [tech-srl/Nero#11]
https://github.com/tech-srl/Nero/blob/3219dd0f5857d984e70787bfbff3506ed3b79c07/datagen/vex2llvm/LLVMCPYBlockSlicer.py#L144

when i use `hashtab_dump_keys` debug code a get the list 
`[(-64, 'ptr_strand'), (%arg.rsp, 'ptr_strand'), (  %ob0.t17 = add %arg.rsp, -64, 'ptr_strand'), (  %.72 = inttoptr %ob0.t17, 'value_strand'), (  %ob0.t40 = load %.72, 'value_strand')]`

But actually its wrong ,and it can be see in ida

![image](https://user-images.githubusercontent.com/31761342/115958760-4d17f000-a53b-11eb-957d-4b9724ff1c4e.png)

ht come from rdi.  from file of llvm_whole_hashtab_dump_keys/hashtab_dump_keys.O2.ll can get source of problem

![image](https://user-images.githubusercontent.com/31761342/115958574-94ea4780-a53a-11eb-8fa3-a891a94a127b.png)

in the the statement "store" must in before of statement "inttoptr" .

actually  should it ">" ?        may I need read the code more.

**Comment by Yanivmd** [comment]
Hey. It seems that you are right. There is a problem here, but it's actually in `extract_writes`. The `inttoptr` needs more delicate treatment. 

If you think you have a solution, by all means, create a PR and I'll look into it.
Otherwise, I will try to solve this as soon as I can.

**Comment by Yanivmd** [comment]
This bug should be solved by the recent update. Please re-open if that is not the case.
