### ISSUE TITLE
IDAPRO gives error if networkx module is imported for CFG

### ISSUE THREAD

**Issue by nav60** [tech-srl/Nero#15]
Respected Sir,
Hopefully you will be fine. I have a query if possible for you to answer. It is related to IDAPRO (IDAPYTHON).  When i use import networkx moduel in the IDAPRO code, i am getting error in the NERO code. I am sharing snapshot with you. 
Any idea how can i use networkx in this way.  I will be thankful for your help. Please
 
The following error come when i import networkx in the code. 
![image](https://user-images.githubusercontent.com/34056389/124267160-52a04080-db51-11eb-923a-e5a7bc6abc99.png)

![image](https://user-images.githubusercontent.com/34056389/124266983-1e2c8480-db51-11eb-9fd7-61b3660ad178.png)

**Comment by Yanivmd** [comment]
Hi. 
As this is not a part of the Nero code, but something you added, It is probably better addressed in a detached manner.
I would advise running these commands from the IDA GUI to see the error. You will probably get an exception of some kind. I would guess you have installed `networkx` in your global python and no the internal python bundles with IDA.

I am closing this issue as it is not related to Nero. Good luck!

**Comment by nav60** [comment]
Hi,
Sir. Thank you for the response and guidance. 👍

**Comment by nav60** [comment]
Hi,
Issue solved after your guidance. Following is the procedure to install any module in IDAPRO 

1. go to python IDA terminal/console and install networkx older version because python is 2.7
2. import pip 
3. pip.main(args=['install', 'networkx<2.0'])

https://stackoverflow.com/questions/45093811/installing-pygraphviz-on-windows-10-64-bit-python-3-6
https://github.com/tmr232/Sark/issues/13
https://github.com/tmr232/Sark/issues/97
