### ISSUE TITLE
Where to reflect the goal is striped binaries?

### ISSUE THREAD

**Issue by puzhuoliu** [tech-srl/Nero#16]
Hi, I have a basic question. The goal of the thesis topic is to stripped binaries. Why is the debugging information used in the learning and testing of the model?

**Comment by Yanivmd** [comment]
We use the debug information as a source for the model to learn from (target labels in training) and to measure the quality of said learning (ground truth in test).

Hope this helps.

**Comment by puzhuoliu** [comment]
Thank you for your reply. Can a binary without debugging information be used for testing?

**Comment by Yanivmd** [comment]
You can and should use stripped binaries for inference. To do that, make sure you replace - https://github.com/tech-srl/Nero/blob/7dac9f5748974ea8f39b5f29bb3c7d33f971077e/collect_and_filter.py#L65 with "return True"

**Comment by puzhuoliu** [comment]
Thanks.
