### ISSUE TITLE
Encountered an error while indexing

### ISSUE THREAD

**Issue by puzhuoliu** [tech-srl/Nero#17]
Hello, I have a question for advice. I used the provided data for indexing and reported the following error.

![error](https://user-images.githubusercontent.com/43575651/136515130-8ebbc5f7-d538-4115-a3a5-ecfb757b98b2.png)

**Comment by Yanivmd** [comment]
Nero's binary analysis pipeline uses LLVM's `opt`. In the reported error the `opt` tool was not found.

Please make sure LLVM 10 is properly installed.
Next, make sure `opt` can be found in $PATH or use the `--llvm-opt-cmd` to point to it.
