### ISSUE TITLE
Some questions about converting assembly language to llvm

### ISSUE THREAD

**Issue by tower111** [tech-srl/Nero#20]
Hi, I found some questions about converting assembly language to llvm.

What to do if the assembly instructions that pass the arguments and call the function are not in the same basic block. Especially the push instruction, the execution flow will determine the variable to pass the parameter

**Comment by Yanivmd** [comment]
If you are following our method, the path extracted from your CFG should not contain branches. Thus, you can always know which value is calculated before being passed as an argument in a call.
