### ISSUE TITLE
pip3 install -r requirements.txt meet an error

### ISSUE THREAD

**Issue by island255** [tech-srl/Nero#3]
I am using ubuntu 20.04 and python 3.8.5 to build the environment. However, as I run the "pip3 install -r requirements.txt", I meet the following error. 

`ERROR: Could not find a version that satisfies the requirement cloud-init==20.2 (from -r requirements.txt (line 17)) (from versions: none)`
`
ERROR: No matching distribution found for cloud-init==20.2 (from -r requirements.txt (line 17))
`

Do you have any idea about it?

**Comment by Yanivmd** [comment]
This has something to do with the install of cairo.

Try running: `sudo apt install libcairo2-dev`, and then trying `pip3 install -r requirements.txt` again should work.

**Comment by island255** [comment]
I have tried this, but it seems not to work.

**Comment by Yanivmd** [comment]
> I have tried this, but it seems not to work.

Sad to hear that. 

I would try:
1. Installing everything in a new virtualenv.
2. Installing the packages by name (the ones mentioned in the README) or using --force.
3. Trying to install the requirements file in verbose mode and debugging that.

**Comment by SeekaMoon** [comment]
Hi, I also encountered this problem but I have solved it. 
Please run the following command to install `cloud-init` on your Ubuntu machine.
`sudo apt install cloud-init`

**Comment by Yanivmd** [comment]
Thank @SeekaMoon!
@island255 Please let me know if @SeekaMoon's suggestion helped resolve this issue. In that case I will add it to the repo's instructions page for the next version.

**Comment by Yanivmd** [comment]
This seems resolved. Reopen if that is not the case.

**Comment by anushka192001** [comment]
> Hi, I also encountered this problem but I have solved it. Please run the following command to install `cloud-init` on your Ubuntu machine. `sudo apt install cloud-init`

but if i want to install specific version of cloud init lets say 22.2?

**Comment by Thauan-th** [comment]
Hey guys I have the same problem and I fixed it by following these steps, if you are trying to deploy your app on heroku then try:

-  Uninstall `django-heroku` and `psycopg2` from their requirements.
- Create another `Virtual Env` and install `django-heroku` only

this worked for me after a lot of research
