### ISSUE TITLE
Docker repository for the convenience of reproduction

### ISSUE THREAD

**Issue by SeekaMoon** [tech-srl/Nero#4]
Nice work. Would you like to provide a docker repository to facilitate the reproduction?

**Comment by Yanivmd** [comment]
Hey @SeekaMoon, thank you for your interest and nice words.
It is definitely on the todo list. If you / someone else want to get to it sooner feel free to say so and we will accept the pull request.

**Comment by SeekaMoon** [comment]
Thanks！
