### ISSUE TITLE
Inconsistent Results of Data Generation Phase

### ISSUE THREAD

**Issue by FiorellaArtuso** [tech-srl/Nero#5]
I am using Ubuntu 16.04, python 3.8, llvm-10 and IDA 7.5. I executed your data generation phase (index_binary.py and collect_and_filter.py) on some of the executables you published (https://zenodo.org/record/4099685/files/nero_dataset_binaries.tar.gz). I then compared the output I obtained with yours (available at https://zenodo.org/record/4095276/files/procedure_representations.tar.gz in the “raw” folder) and I noticed that they do not seem to match. In particular, I noticed three main differences:

- The first difference is given by the json format. The format provided by your results is incompatible with the format expected by the preprocess.py module, whereas the format I obtained is correct with respect to that module.

- The second difference (even if irrelevant) is given by the json field “package”. In your results this field is simply composed by the package name, whereas in the results I obtained is composed in the following way “<function_name>@<exe_name>@<package_name>”

- The third difference consists in  having different nodes and edges in some functions. Below an example for “server_main_loop” function inside the “gcc-5__Ou__mtools__floppyd” executable:

  `{"exe_name": "floppyd", "package": "server_main_loop@floppyd@mtools", "func_name": "server_main_loop", "GNN_data": {"nodes": {"ob-1.initialize": "{\"py/set\": [{\"py/tuple\": [{\"py/tuple\": [\"Esignal\", {\"py/tuple\": [\"CONST\", 17]}, {\"py/tuple\": [\"CONST\", 1]}]}]}]}", "ob1": "{\"py/set\": []}", "ob2": "{\"py/set\": [{\"py/tuple\": [{\"py/tuple\": [\"Eaccept\", {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}]}]}]}", "ob3": "{\"py/set\": [{\"py/tuple\": [{\"py/tuple\": [\"Efork\", {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", -48]}, {\"py/tuple\": [\"CONST\", -40]}]}]}]}", "ob4": "{\"py/set\": []}", "ob5": "{\"py/set\": [{\"py/tuple\": [{\"py/tuple\": [\"Nserve_client\", {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", 0]}]}, {\"py/tuple\": [\"Eexit\", {\"py/tuple\": [\"CONST\", 0]}]}]}]}", "ob7": "{\"py/set\": []}"}, "edges": [{"py/tuple": ["FakeRoot", "ob-1.initialize"]}, {"py/tuple": ["ob-1.initialize", "ob1"]}, {"py/tuple": ["ob1", "ob2"]}, {"py/tuple": ["ob2", "ob3"]}, {"py/tuple": ["ob2", "ob2"]}, {"py/tuple": ["ob3", "ob4"]}, {"py/tuple": ["ob3", "ob7"]}, {"py/tuple": ["ob4", "ob7"]}, {"py/tuple": ["ob4", "ob5"]}, {"py/tuple": ["ob5", "FakeSink"]}, {"py/tuple": ["ob7", "ob1"]}]}}`

  Whereas this is the result you published:

  `{"func_name": "server_main_loop", "GNN_data": {"nodes": {"ob-1.initialize": {"py/set": ["[{\"py/tuple\": [\"Esignal\", {\"py/tuple\": [\"CONST\", 17]}, {\"py/tuple\": [\"CONST\", 1]}]}]"]}, "ob7": {"py/set": []}, "ob4": {"py/set": []}, "ob5": {"py/set": ["[{\"py/tuple\": [\"Nserve_client\", {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", 0]}]}, {\"py/tuple\": [\"Eexit\", {\"py/tuple\": [\"CONST\", 0]}]}]"]}, "ob2": {"py/set": ["[{\"py/tuple\": [\"Eaccept\", {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}, {\"py/tuple\": [\"CONST\", \"\"]}]}]"]}, "ob3": {"py/set": ["[{\"py/tuple\": [\"Efork\"]}]"]}, "ob1": {"py/set": []}}, "edges": [{"py/tuple": ["ob-1.initialize", "ob1"]}, {"py/tuple": ["FakeRoot", "ob-1.initialize"]}, {"py/tuple": ["ob7", "ob1"]}, {"py/tuple": ["ob4", "ob7"]}, {"py/tuple": ["ob4", "ob5"]}, {"py/tuple": ["ob5", "FakeSink"]}, {"py/tuple": ["ob2", "ob2"]}, {"py/tuple": ["ob2", "ob3"]}, {"py/tuple": ["ob3", "ob7"]}, {"py/tuple": ["ob3", "ob4"]}, {"py/tuple": ["ob1", "ob2"]}]}, "exe_name": "floppyd", "package": "mtools"}`

  As you can see, in both cases, node ob3 contains the fork function. Nevertheless, my result shows 4 arguments for that function whereas your result correctly shows no argument.

Moreover, some errors prevented me to execute the code as it is, these are my fixes 

- Rows 27 and 28 of collect_and_filter.py contain wrong imports. The correct ones are:
```
from datagen. files import IndexedExeFile, IndexedExeFileZip
from datagen.ida.proc_name_cleanup import get_no_prefix_suffix_proc_name
```

- Row 59 of datagen/ida/py2/bin_extract.py contains a typing mistake: logging.exception(eessage).

- You assume input directory for index_binaries.py to be organized as follow: “Objects -> projects* -> exes*”. However, the dataset you provide does not contain subfolders.

I do not think that these fixes are the root of the inconsistencies . Also the version 7.5 of IDA should not be the culprit.  
Many thanks for your help!

**Comment by Yanivmd** [comment]
Hey @FiorellaArtuso. 
Thank you for the feedback and detailed report regarding these issues.
Most of these issues resulted from the steps we took to make the project easier to use and be compatible on current software. Specifically, one of these steps was porting to python3 which caused most of the issues you had reported.

We will fix the library debug information cache (which caused the wrong number of `fork` arguments) and other issues towards an updated version.

Regarding the JSON incompatibility: you should be able to use the preprocessed data from the Zenodo files for training using the code in 'model' directory.

**Comment by Yanivmd** [comment]
Closing this after pushing the fix. If these problems persist reopen/open a new issue.
