### ISSUE TITLE
issue in data generation part of the project

### ISSUE THREAD

**Issue by nav60** [tech-srl/Nero#7]
Hi,
Sir.
First of all, thank you for sharing brilliant work with the community.  I am setting environment by following instructions given.  I am using **Ubuntu 20.20** with **python 3.8, llvm-10 and IDA version 7.0** from https://github.com/AngelKitty/IDA7.0 . 
I am also using your shared binary set (https://zenodo.org/record/4099685/files/nero_dataset_binaries.tar.gz) and extracted inside the Nero-main code.  
In my case, installation of the IDA is at **/opt/idafree-7.0/ida64** and **jsonpickle** placed at /opt/idafree-7.0/python.

After setting the required environment, following command is executed in the terminal 
 _python3.8 -u index_binaries.py --debug -v --input-dir TRAIN --output-dir TRAIN_INDEXED --idal64-path=/opt/idafree-7.0/ida64_
![output](https://user-images.githubusercontent.com/34056389/107110170-8bb8db00-6867-11eb-852d-65588f2bebe6.PNG)

There is no output in the TRAIN_INDEXED directory as shown in the attached image.

please guide me to sort out this issue.

**Comment by nav60** [comment]
Update:
As it is mentioned in the already open issue ( https://github.com/tech-srl/Nero/issues/5 ), sub-folder are missing in the given TRAIN directory.
First of all create sub-directory Objects and then projects and then all exes in this folder. I have also used -v switch to understand the problematic point.

Now, i am getting error due to unlicensed version of the IDA software.

**Comment by Yanivmd** [comment]
Hi @nav60,
Make sure to pull from the repo again as some of the issues you reported above are fixed :)

Regarding the IDA-7 version, did you get IDA-python to work with it? I think that officially it does not contain support for IDA-python.

**Comment by nav60** [comment]
Hi @Yanivmd 
Sir, Thank you for response. 
Thank you for fixes. I have skipped Data Generation part and used your json files etc. Yes. IDA-7 does not support python.
Sir. there were few path issues occurred during testing of 2nd part of the project. However, i have fixed those at my end. 

Sir. one more information is required if possible for you to answer. I have seen paper of FiorellaArtuso ( https://arxiv.org/pdf/1912.07946v3.pdf  ) and they have used their research on the malicious binaries as well. 

Can we use same malicious binaries to test your project.  Can you please correct me if i am thinking in wrong way, Please

**Comment by Yanivmd** [comment]
@nav60, you can try using this prototype with malicious binaries.

**Comment by nav60** [comment]
@Yanivmd  Thank you sir. okay
