### ISSUE TITLE
How do you modify the DIRE model to predict function names

### ISSUE THREAD

**Issue by SeekaMoon** [tech-srl/Nero#8]
Hi, I notice that you write in the paper that you have modified the DIRE model to predict function names and used the modified model as a baseline for comparison. However, the DIRE model can only predict local variable names, and the authors of it have not released their code yet (they only release the generated representations). It seems that you do not describe the details of the modification in your paper too.

I would like to know how you get the code of DIRE and modify it. Is it convenient to release the code of the modified model?

Thanks!

**Comment by Yanivmd** [comment]
Hi @SeekaMoon. 

I will go over my files and see if I could find a stable version of the changed code. It did require changing the data-gen and NN architecture.

In the meantime, please note that the authors did release their code and you can find it [here](https://github.com/CMUSTRUDEL/DIRE)

**Comment by SeekaMoon** [comment]
Thank you for your prompt reply! 
I have carefully checked the DIRE paper and corresponding ASE page but do not find the code link (only the dataset link). So I guess that they do not release the code. Anyhow, thank you for providing their code link. It does help me :-)
