### ISSUE TITLE
there are som problem

### ISSUE THREAD

**Issue by tower111** [tech-srl/Nero#9]
https://github.com/tech-srl/Nero/blob/7dd3b162dd3516ea336386576d73712e42752c99/datagen/vex2llvm/proc_translator.py#L70

I conn't find about "vex_reg_offset_to_name" , and code error.

maybe i can replace it to `self._ret_register_name="rax"`

**Comment by Yanivmd** [comment]
What CPU architecture are the binaries you are trying to analyze?
What angr/vex version are you using?

You can probably get away with replacing with "rax", but other parts might break if you are using other versions.

**Comment by Yanivmd** [comment]
As you submitted other questions I think that this problem is already solved @tower111 ?

**Comment by Yanivmd** [comment]
Closed by #13. Thanks @tower111 .
